### ISSUE TITLE
TypeError: __init__() takes at least 3 arguments (2 given)

### ISSUE THREAD

**Issue by wikijm** [samuelclay/Raspberry-Pi-Photo-Frame#7]
I have this error message when I try to use the download_flickr.py script:

```
pi@RaspAP3:~/photoframe $ python download_flickr.py
 ---> Requesting photos...                                         
Traceback (most recent call last):
  File "download_flickr.py", line 36, in <module>
         main()
  File "download_flickr.py", line 20, in main
         flickr = flickrapi.FlickrAPI(FLICKR_KEY)
TypeError: __init__() takes at least 3 arguments (2 given)
```

I modified FLICKR_KEY and USER_ID.
What did I miss?

**Comment by samuelclay** [comment]
What version of the flickr python lib are you using? I bet I just haven't updated it in a long time.

**Comment by wikijm** [comment]
pi@RaspAP3:~ $ pip show flickrapi
Name: flickrapi                                                    Version: 2.1.2
Summary: The Python interface to the Flickr API
Home-page: http://stuvel.eu/projects/flickrapi
Author: Sybren A. Stuvel
Author-email: sybren@stuvel.eu
License: Python
Location: /usr/local/lib/python2.7/dist-packages
Requires: requests-toolbelt, six, requests-oauthlib, requests

**Comment by wikijm** [comment]
pi@RaspAP3:~ $ sudo pip install requests-toolbelt six requests-oauthlib requests
Requirement already satisfied: requests-toolbelt in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages
Requirement already satisfied: oauthlib>=0.6.2 in /usr/local/lib/python2.7/dist-packages (from requests-oauthlib)

**Comment by samuelclay** [comment]
Try flickerapi==1.4.4, which is what I have installed.

**Comment by wikijm** [comment]
With flickrapi v1.4.4:

```
root@kali:~/photoframe# sudo python download_flickr.py 
 ---> Requesting photos...
 ---> Downloading http://farm9.staticflickr.com/8506/29340091235_9aee3f876b_z.jpg
Traceback (most recent call last):
  File "download_flickr.py", line 35, in <module>
    main()
  File "download_flickr.py", line 30, in main
    image_file = open(path, 'w')
IOError: [Errno 2] No such file or directory: '/home/pi/photoframe/flickr/29340091235_9aee3f876b_z.jpg'
```
