### ISSUE TITLE
[Request][download_flickr.py] Rename jpeg file like picture title

### ISSUE THREAD

**Issue by wikijm** [samuelclay/Raspberry-Pi-Photo-Frame#8]
Is it possible to downloadd and rename jpeg with picture title?
My final goal: Show picture on TFT screen, with the title of the picture at the bottom of the screen, thanks to "fbi" program.

**Comment by samuelclay** [comment]
That's a good question. I don't think fbi can handle that. I would look at FIM: http://www.nongnu.org/fbi-improved/. 

If you get it working with FIM, please submit a PR. I'd love to integrate that.
